apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    app: nginx-app
data:
  meroapp.conf: |
    server {
      listen 80;

      location / {
          proxy_pass http://192.168.56.110:3000/gogs/bucket/raw/master/some.txt;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /image {
          proxy_pass http://192.168.56.110:3000/gogs/bucket/raw/master/image.jpeg;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

