apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k3s-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx/conf.d/default.conf"
              name: nginx-configmap-volume
              subPath: meroapp.conf 
      volumes:
        - name: nginx-configmap-volume
          configMap:
            name: nginx-configmap

